
    MACRO SET_BORDER_COLOUR
	    out (PORT_SPECTRUM_ULA),a
	ENDM

	MACRO PERF_BORDER_COLOUR colour
        IF DISPLAY_PERFORMANCE_DEBUG_BORDER
        	ld a,colour
        	SET_BORDER_COLOUR
        ENDIF
	ENDM

    MACRO SHOW_SPRITES
	    nextreg NEXTREG_SPRITES_AND_LAYERS_SYSTEM, NEXTREG_SPRITES_AND_LAYERS_SYSTEM_FLAG_SHOW_SPRITES|NEXTREG_SPRITES_AND_LAYERS_SYSTEM_FLAG_SPRITES_OVER_BORDER
	ENDM

    MACRO HIDE_SPRITES
	    nextreg NEXTREG_SPRITES_AND_LAYERS_SYSTEM, 0
	ENDM	
	