
; invaders.afb effect indices
SOUND_EFFECT_INDEX_SHIP_SHOT         EQU 0
SOUND_EFFECT_INDEX_INVADER_DESTROYED EQU 1
SOUND_EFFECT_INDEX_SHIP_DESTROYED    EQU 2
SOUND_EFFECT_INDEX_UFO_SIREN         EQU 3
SOUND_EFFECT_INDEX_UFO_DESTROYED     EQU 4
SOUND_EFFECT_INDEX_EXTRA_LIFE        EQU 5

SOUND_EFFECT_CHANNEL_SHIP            EQU 0
SOUND_EFFECT_CHANNEL_INVADER         EQU 1
SOUND_EFFECT_CHANNEL_UFO             EQU 2
SOUND_EFFECT_CHANNEL_EXTRA_LIFE      EQU 2  ; same as UFO for now. TODO: Support 6 channels and use free channel
