
; 256x192 pixels at 1 bit per pixel = $1800 bytes
; 32x24 8x8 attribute cells AT 1 byte per cell = $300 bytes
; https://wiki.specnext.dev/Video_Modes#Spectrum_Video_Mode

ULA_BITMAP_WIDTH_PIXELS  EQU 256
ULA_BITMAP_HEIGHT_PIXELS EQU 192

ULA_BITMAP_WIDTH_BYTES EQU 32 ; 1 bit per pixel = 8 pixels per byte

ULA_BITMAP_SIZE_BYTES EQU ULA_BITMAP_WIDTH_BYTES * ULA_BITMAP_HEIGHT_PIXELS
    ASSERT ULA_BITMAP_SIZE_BYTES == $1800 ; known value

ULA_BITMAP_ADDRESS EQU $4000

ULA_ATTRIBUTES_ADDRESS EQU ULA_BITMAP_ADDRESS + ULA_BITMAP_SIZE_BYTES
    ASSERT ULA_ATTRIBUTES_ADDRESS == $5800 ; known value

ULA_ATTRIBUTES_WIDTH_BYTES EQU 32
ULA_ATTRIBUTES_HEIGHT_BYTES EQU 24
ULA_ATTRIBUTES_SIZE_BYTES EQU ULA_ATTRIBUTES_WIDTH_BYTES * ULA_ATTRIBUTES_HEIGHT_BYTES
    ASSERT ULA_ATTRIBUTES_SIZE_BYTES == $300; known value

;-------------------------------------------------------------------------------------------------------
; Colour palette (ULA)
;
;            GRB
BLACK   EQU %000
BLUE    EQU %001
RED     EQU %010
MAGENTA EQU %011
GREEN   EQU %100
CYAN    EQU %101
YELLOW  EQU %110
WHITE   EQU %111

ATTR_INK_BLACK   EQU BLACK
ATTR_INK_BLUE    EQU BLUE
ATTR_INK_RED     EQU RED
ATTR_INK_MAGENTA EQU MAGENTA
ATTR_INK_GREEN   EQU GREEN
ATTR_INK_CYAN    EQU CYAN
ATTR_INK_YELLOW  EQU YELLOW
ATTR_INK_WHITE   EQU WHITE

ATTR_PAPER_BLACK    EQU 0x00
ATTR_PAPER_BLUE     EQU 0x08
ATTR_PAPER_RED      EQU 0x10
ATTR_PAPER_MAGENTA  EQU 0x18
ATTR_PAPER_GREEN    EQU 0x20
ATTR_PAPER_CYAN     EQU 0x28
ATTR_PAPER_YELLOW   EQU 0x30
ATTR_PAPER_WHITE    EQU 0x38

ATTR_BRIGHT_BIT EQU 6
ATTR_BRIGHT EQU 0x40
ATTR_FLASH  EQU 0x80

